### ISSUE TITLE
Change user-agent

### ISSUE THREAD

**Issue by gi-yt** [emacs-eaf/eaf-browser#21]
# Add a way to change the user-agent
The fact that eaf browser uses a very rare user agent (QtWebengine 5) makes it very easy for fingerprinting
**I would like a var in elisp which i can set in my config.**
**When i used normal browsers I used to use extensions to do it but sadly eaf doesnt support them**

**Comment by manateelazycat** [comment]
eaf-browser-pc-user-agent and eaf-browser-phone-user-agent
