### ISSUE TITLE
Prevent browser from invert images in dark-mode?

### ISSUE THREAD

**Issue by taquangtrung** [emacs-eaf/eaf-browser#23]
Hi,

**Describe the bug**

I'm using eaf-browser in dark-mode (follow mode) and see that when images are inverted, they are very difficult to see, like in the below screenshot:

![browser](https://user-images.githubusercontent.com/193967/135251389-f45d2091-4ef3-40f4-ab2b-65739db72b91.png)

**To Reproduce**

Use eaf-browser to browse the website: https://caml.inria.fr/pub/docs/u3-ocaml/ocaml-mixins.html

and scroll down to see the inverted image.

**Expected behavior**

Images shouldn't be inverted

**Comment by manateelazycat** [comment]
Image is not inverted, because it's background is transparent. 

https://caml.inria.fr/pub/docs/u3-ocaml/ocaml007.gif

I think nothing to do with this issue.

**Comment by taquangtrung** [comment]
Oh, I see. Thanks for pointing it out
