### ISSUE TITLE
Cannot use `C-n`, `C-p`, `prior`, `next` to scroll some websites

### ISSUE THREAD

**Issue by taquangtrung** [emacs-eaf/eaf-browser#25]
Hi,

**Describe the bug**

EAF-browser can not scroll some websites by pressing the `C-n`, `C-p`, `prior`, `next` keys.

**To Reproduce**

- Browse this website by Eaf-browser:

  https://stevedonovan.github.io/rust-gentle-intro/1-basics.html

  and then press `C-n`, `C-p`, `prior`, or `next`,

- No action will be performed. 

**Expected behavior**

The website should be scrolled accordingly.

**Versions (please complete the following info):**
 - Distro and DE/WM:
 - Versions of Dependencies:
 - M-x emacs-version: 28.0.50

**Comment by MatthewZMD** [comment]
The problem has to do with JS functions like `document.scrollingElement.scrollBy(0, 50)` not working in this webpage, it is not a problem on EAF, you can try in devtools yourself and compare the results in this site and other sites.

However, if you have time, you could try to investigate a better command to control website movements, maybe investigate how vimium handles it.

**Comment by taquangtrung** [comment]
@MatthewZMD: thanks for the suggestions on vimium!

I also did a quick investigation previously, but still don't know why those Javascript scrolling functions don't work with that website.

**Comment by MatthewZMD** [comment]
> @MatthewZMD: thanks for the suggestions on vimium!
> 
> I also did a quick investigation previously, but still don't know why those Javascript scrolling functions don't work with that website.

Yeah, it probably has to do with how the site was written.

**Comment by manateelazycat** [comment]
Because current use JS scroll page, it will failed on some website, we should send wheel_scroll Qt event to EAF widget, then this issue will fixed.

**Comment by manateelazycat** [comment]
Fixed by patch https://github.com/emacs-eaf/emacs-application-framework/commit/88a3bef4c1204d5efc04709f37857d7ac5582364

Thanks for patch.

**Comment by taquangtrung** [comment]
@manateelazycat: awesome! Thanks a lot for the update. 

Now I can scroll the website https://stevedonovan.github.io/rust-gentle-intro/ by C-n, C-p effortlessly!
