### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt5'

### ISSUE THREAD

**Issue by ucsky** [emacs-eaf/eaf-browser#26]
Hello, after installing EAF and browser application I get:

```
Traceback (most recent call last):
  File "/home/ucsky/.emacs.d/site-lisp/emacs-application-framework/eaf.py", line 25, in <module>
    from PyQt5 import QtWebEngineWidgets as NeverUsed # noqa
ModuleNotFoundError: No module named 'PyQt5'

Process *eaf* exited abnormally with code 1
```
Ubuntu version:
```
LSB Version:	core-11.1.0ubuntu2-noarch:security-11.1.0ubuntu2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```
Emacs version:
```
GNU Emacs 26.3
```

**Comment by MatthewZMD** [comment]
it seems like your dependency is not installed correctly. Did you run `install-eaf.py`? what is the output?

**Comment by manateelazycat** [comment]
Please use install-eaf.py install depend like https://github.com/emacs-eaf/emacs-application-framework README said.

**Comment by ucsky** [comment]
Yes I did install it with `install-eaf.py`. Sorry didn't had the time to re-run it for get you the log.
