### ISSUE TITLE
Calling caret_at_line does not display the marked region

### ISSUE THREAD

**Issue by Gira-X** [emacs-eaf/eaf-browser#28]
I think it's easiest to just follow the video. The first call to `eaf-py-proxy-caret_at_line` should display a marked region but there is none.

Calling `eaf-py-proxy-caret_toggle_mark` afterwards seems to work, but because `_caret_at_line` calls `self.buffer.caret_next_word()`, the caret position is off one word.

https://user-images.githubusercontent.com/15002298/147147594-dc4ba756-9e41-40c4-bad5-cf7e5a34caaa.mov

**Comment by manateelazycat** [comment]
@Gira-X I rarely use the caret function, welcome to PR ;)
