### ISSUE TITLE
Can't play any video in the browser

### ISSUE THREAD

**Issue by knarkzel** [emacs-eaf/eaf-browser#34]
**\*eaf\***
```
Dexie.delete('webtorrent-chunks-a7370e12ba0af21988647bb5fde350a5fba5a0fe') was blocked
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. [object Object]
[object DOMException]
```

**Describe the bug**
When trying to play any video in the browser, I get "The media could not be loaded, ether because the server or network failed or because the format is not supported.

**To Reproduce**
I'm on master branch: de18acc

**Expected behavior**
Playing video should work.

**Versions (please complete the following info):**
 - Arch Linux x86_64, dwm
 - Versions of Dependencies:
 - GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.17.4) of 2021-11-28

**Screenshots**

- https://imgur.com/a/eMxKMHw

**Comment by manateelazycat** [comment]
I think it's your system problem, some video decodec not install ;)
