### ISSUE TITLE
Firefox extensions (add-on) support

### ISSUE THREAD

**Issue by Ghibranalj** [emacs-eaf/eaf-browser#36]
**Is your feature request related to a problem? Please describe.**
I want to daily drive eaf-browser, but there are a few extension i just cant live without

**Describe the solution you'd like**
It would be a nice if i can install extensions. either by using the web app by firefox or if i have to install it manually it would be fine also

**Describe alternatives you've considered**
I tried looking for additional emacs packages to no avail

**Additional context**
\-

**Comment by manateelazycat** [comment]
no, eaf broswer is base on chromium, not support firefox extension or chromium extension

**Comment by Ghibranalj** [comment]
Mine is definitely firefox

**Comment by Ghibranalj** [comment]
My user agent is definitely firefox when im using eaf-browser

**Comment by manateelazycat** [comment]
just user agent, but not support firefox extension like i said

**Comment by MatthewZMD** [comment]
The user agent is customizable to leave less internet footprint
