### ISSUE TITLE
Eaf browser open in new frame instead of inside buffer on emacs 29

### ISSUE THREAD

**Issue by Ghibranalj** [emacs-eaf/eaf-browser#37]
- If EAF was working correctly until a recent `git pull`, please refer to [Mandatory Procedures to Keep Your EAF Up-to-Date](https://github.com/manateelazycat/emacs-application-framework/discussions/527?sort=new) first.
- Please check the `*eaf*` buffer, if there is any error shown in the `*eaf*` buffer, paste it here.
```
QXcbConnection: XCB error: 3 (BadWindow), sequence: 10845, resource id: -1396455504, major code: 7 (ReparentWindow), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 10956, resource id: -1396455504, major code: 7 (ReparentWindow), minor code: 0
QXcbConnection: XCB error: 3 (BadWindow), sequence: 11684, resource id: -1396455504, major code: 7 (ReparentWindow), minor code: 0
....repeating
````
**Describe the bug**
when opening eaf browser on emacs 29 it opens it on a frame instead of buffer. The buffer where it suppose to render will be blank.

**To Reproduce**
Open eaf-browser using `(eaf-open-browser)`

**Expected behavior**
it should be rendered inside the buffer

**Versions (please complete the following info):**
 - Distro and DE/WM: Arch linux on gnome 42
 - Versions of Dependencies: node 16 python
 - M-x emacs-version: "GNU Emacs 29.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.34, cairo version 1.17.6)\n of 2022-07-19"

**Screenshots**
![Screenshot from 2022-07-19 22-43-17](https://user-images.githubusercontent.com/24712554/179845265-7efa06bc-e29a-4745-bcdc-c98d635c5259.png)
**Additional context**
I just upgraded from emacs 28 to 29.

**Comment by manateelazycat** [comment]
wayland still not support

**Comment by Ghibranalj** [comment]
I am on X11. It works before i updated to emacs 29

**Comment by MatthewZMD** [comment]
Can you try to downgrade to emacs28 and see if it is working again? Just to verify that it is emacs 29 messing up things.

If so, we might not do anything at the moment, emacs 29 is at its very early stage and there are changes every single day, it is unrealistic for us third-party libraries to support the master branch atm.

**Comment by manateelazycat** [comment]
Because wayland not allow EAF reparent on Emacs, we can't use xreparent technology.

Because wayland not allow get active application window, we can use toplevel Qt window technology like macOS.

Sorry, we nothing can do for Wayland.

You upgrade to Emacs 29 that Emacs developer enable pgtk default, please re-compile Emacs without pgtk option if you want use Emacs 29.
