### ISSUE TITLE
'eaf-import-chrome-bookmarks' triggers 'wrong-number-of-arguments' error

### ISSUE THREAD

**Issue by benthamite** [emacs-eaf/eaf-browser#38]
**Describe the bug**
Invoking `eaf-import-chrome-bookmarks` results in a `wrong-number-of-arguments` error.

**Expected behavior**
Bookmarks are imported

Inspecting [the Emacs Lisp command](https://github.com/emacs-eaf/eaf-browser/blob/master/eaf-browser.el#L663), it looks like this is simply because `eaf-read-input` takes four arguments, but only three are passed to it. Replacing `(when (eaf-read-input "Are you sure to import chrome bookmarks to EAF" "yes-or-no" "")` with `(when (eaf-read-input "Are you sure to import chrome bookmarks to EAF" "yes-or-no" "" "")` solves the issue. (The same fix should be applied to the [Firefox command](https://github.com/emacs-eaf/eaf-browser/blob/master/eaf-browser.el#L416).)

**Comment by manateelazycat** [comment]
Can you help send PR to fixed this?

Thanks. ;)
