### ISSUE TITLE
Feature toggle_dark_mode seems to be broken

### ISSUE THREAD

**Issue by taquangtrung** [emacs-eaf/eaf-browser#44]
Hi,

**Describe the bug**

It seems that the function `toggle_dark_mode` is broken for eaf-browser.

**To Reproduce**

- Load any website by eaf-browser in dark mode. 
- Press `M-d` to toggle the dark mode.
- The website is reloaded but is still in the dark mode, not in normal mode.

**Expected behavior**

The dark mode should be disabled.

**Versions (please complete the following info):**
 - Distro and DE/WM: Linux Mint 22.
 - M-x emacs-version: 28.2

**Comment by manateelazycat** [comment]
Fixed by https://github.com/emacs-eaf/emacs-application-framework/commit/f97b9a8d373662a5a13e0c080e81c229707df225
