### ISSUE TITLE
cannot login google site

### ISSUE THREAD

**Issue by csfreebird** [emacs-eaf/eaf-browser#46]
**Describe the bug**
when trying to log in google site, get the following response:

无法登录
此浏览器或应用可能不安全。 了解详情
请尝试使用其他浏览器。如果您使用的是受支持的浏览器，可以重新尝试登录。

**Screenshots**
![image](https://user-images.githubusercontent.com/870486/208289277-02901e94-cefb-4a70-88a5-913ebbdfe9d1.png)

**Additional context**
ubuntu 22.04, newest eaf

**Comment by manateelazycat** [comment]
可以先试一下 
eaf-py-proxy-delete_cookie
或
eaf-py-proxy-delete_all_cookies

看看清空cookie重新登录会不会好？

**Comment by csfreebird** [comment]
M-x eaf-py-proxy-clear_cookies 执行失败

没有找到eaf-py-proxy-delete_cookie 命令

Traceback (most recent call last):
  File "/home/dean/.emacs.d/elpa/28.1/develop/eaf-20221110.2200/eaf.py", line 368, in eval_function
    getattr(buffer, function_name)()
AttributeError: 'AppBuffer' object has no attribute 'clear_cookies'

**Comment by manateelazycat** [comment]
你这个看着完全是安装的问题，为啥不按照README的方式安装呢？

其他包管理器安装的方式都是错误的。
