### ISSUE TITLE
看不了优酷视频

### ISSUE THREAD

**Issue by djexu1981** [emacs-eaf/eaf-browser#54]
用eaf-browser打开www.youku.com网站，点击上面的视频，显示加载失败。

**Comment by manateelazycat** [comment]
什么系统？

**Comment by djexu1981** [comment]
manjaro linux

**Comment by djexu1981** [comment]
错误参见截图
![youku_error](https://user-images.githubusercontent.com/18548520/223694489-ba7c985d-03f8-412e-8525-4eaced64263c.png)

**Comment by djexu1981** [comment]
@manateelazycat 你好，在macos里试了一下也是同样问题。

**Comment by manateelazycat** [comment]
你估计是你 ffmpeg 的问题， 导致你的Qt没有正确的视频解码器。

**Comment by djexu1981** [comment]
应该不是ffmpeg的问题，我用qutebrowser没这个问题，qutebrowser也是用qtwebengine开发的。
可能和qtwebengine的版本有关，eaf-browser用的是qt6-webengine，qutebrowser用的是qt5-webengine。

**Comment by csfreebird** [comment]
我的eaf browser是能看youtube视频，但无法登录。作者显然也不想解决问题，每次都是快速的close掉我的issue。解决问题的一个方法就是干掉问题本身，有些人深谙此道。
看了这个issue，试用了一下qutebrowser，很好，没什么毛病，是个真正的产品。
感谢楼上。
eaf 果断弃坑。

**Comment by manateelazycat** [comment]
> 我的eaf browser是能看youtube视频，但无法登录。作者显然也不想解决问题，每次都是快速的close掉我的issue。解决问题的一个方法就是干掉问题本身，有些人深谙此道。 看了这个issue，试用了一下qutebrowser，很好，没什么毛病，是个真正的产品。 感谢楼上。 eaf 果断弃坑。

用户的环境很复杂， 看不了视频跟很多问题都有关系。

为什么你认为一个开源软件必须免费给你服务呢？ 什么补丁都没法为什么要这么说话呢。

**Comment by csfreebird** [comment]
> > 我的eaf browser是能看youtube视频，但无法登录。作者显然也不想解决问题，每次都是快速的close掉我的issue。解决问题的一个方法就是干掉问题本身，有些人深谙此道。 看了这个issue，试用了一下qutebrowser，很好，没什么毛病，是个真正的产品。 感谢楼上。 eaf 果断弃坑。
> 
> 用户的环境很复杂， 看不了视频跟很多问题都有关系。
> 
> 为什么你认为一个开源软件必须免费给你服务呢？ 为什么要把你的快乐建立在别人免费服务还要给你服务100分呢？
> 
> 什么补丁都没发，为什么要这么说话呢？你觉得你这样说话合适吗？

你连续两次快速关闭issue，这么做有礼貌么？
我两次都尽量提供了详细的信息，试图帮助你完善产品，但为什么两次都是被简单一句话打发，然后就关闭issue呢。
这种行为在github很少见。
不会再回应你的话。

**Comment by manateelazycat** [comment]
@djexu1981 这个问题请按照 https://emacs-china.org/t/emacs-linux-windows-mac-bsd/6199/2615?u=manateelazycat 这里的提示来尝试， 应该是修复好了。
