### ISSUE TITLE
overflow

### ISSUE THREAD

**Issue by Arian-p1** [emacs-eaf/eaf-browser#55]
only I can just say sometimes when I open more than 3 windows with different links it starts to overflow and take all of my memory 
I couldn't take screenshots because when it happen my laptop became like turtle

**Comment by manateelazycat** [comment]
emacs -Q for compare test.

**Comment by MatthewZMD** [comment]
How much memory do you have?

**Comment by Arian-p1** [comment]
> 

12g

**Comment by Arian-p1** [comment]
eman 

> emacs -Q for compare test.

this just show me emacs without config

**Comment by namgo** [comment]
@Arian-p1 not a project contributor, just jumping in to suggest that it could be your config that's causing a problem.

`emacs -Q` would be helpful to confirm that it's emacs-eaf at fault and not a configuration issue.

**Comment by Arian-p1** [comment]
@namgo thsnks for suggest but it was the default configs with doom and I dont use emacs anymore so I will close this issue
