### ISSUE TITLE
无法登录google

### ISSUE THREAD

**Issue by csfreebird** [emacs-eaf/eaf-browser#56]
已经调整为readme的安装方式，卸载了原来spacemacs eaf layer

![image](https://user-images.githubusercontent.com/870486/226827091-5ed64c32-4e74-42ac-a13a-500a994b32b4.png)

但问题依然存在

也已经使用了命令eaf-py-proxy-delete_cookie删除cookie, 没有解决问题。

**Comment by manateelazycat** [comment]
自己换一下 UA 吧， https://github.com/emacs-eaf/emacs-application-framework/blob/baf64ffdd488e8d8f9a94a4b1b043f060e0fd1d3/eaf.el#L413
