### ISSUE TITLE
[wishlist] save current web page to a file ?

### ISSUE THREAD

**Issue by fenix011** [emacs-eaf/eaf-browser#58]
**Is your feature request related to a problem? Please describe.**
To be added to the wishlist? Would it be possible to save the current web page to a file ?

**Describe the solution you'd like**
I would love to be able to save the current web page to a file ?

**Describe alternatives you've considered**
Even better ... to save the current web page as a markdown or orgmode file ?

**Comment by manateelazycat** [comment]
org-w3m
