### ISSUE TITLE
eaf-browser bilibili 

### ISSUE THREAD

**Issue by tutict** [emacs-eaf/eaf-browser#67]
![图片](https://github.com/emacs-eaf/eaf-browser/assets/70006802/b52db336-eb4d-48b2-92cd-005a68e6bdbd)

求解

**Comment by manateelazycat** [comment]
https://manateelazycat.github.io/2023/05/13/eaf-browser-html5-video/

https://manateelazycat.github.io/2023/07/08/eaf-browser-ubuntu/
