### ISSUE TITLE
部分正则表达式在 python 3.12 中出现错误

### ISSUE THREAD

**Issue by bbenchen** [emacs-eaf/eaf-browser#70]
https://github.com/emacs-eaf/eaf-browser/blob/1c0076cca287c384f46e5104365f679e94135734/buffer.py#L195

python3.12 SyntaxWarning: invalid escape sequence '\\?'

https://github.com/emacs-eaf/eaf-browser/blob/1c0076cca287c384f46e5104365f679e94135734/buffer.py#L203

python3.12 SyntaxWarning: invalid escape sequence '\s'

**Comment by manateelazycat** [comment]
Thanks for report.
