### ISSUE TITLE
can not open chatgpt.com

### ISSUE THREAD

**Issue by JDLu2003** [emacs-eaf/eaf-browser#73]
- If EAF was working correctly until a recent `git pull`, please refer to [Mandatory Procedures to Keep Your EAF Up-to-Date](https://github.com/manateelazycat/emacs-application-framework/discussions/527?sort=new) first.
- Please check the `*eaf*` buffer, if there is any error shown in the `*eaf*` buffer, paste it here.

**Describe the bug**

**To Reproduce**
Ensure you're on the latest master branch, then note the steps to reproduce the behavior.

**Expected behavior**

**Versions (please complete the following info):**
 - Distro and DE/WM:
 - Versions of Dependencies:
 - M-x emacs-version:

**Screenshots**

**Additional context**
![Uploading image.png…]()

**Comment by JDLu2003** [comment]
EAF] Browser https://chatgpt.com/ loading time: 1.7455766201019287s
[EAF] Browser https://chatgpt.com/ loading time: 0.5034723281860352s
[EAF] Browser https://chatgpt.com/ loading time: 0.520885705947876s
[EAF] Browser https://chatgpt.com/ loading time: 0.41702914237976074s

**Comment by MatthewZMD** [comment]
Can't reproduce, are you able to open other websites?

**Comment by JDLu2003** [comment]
thank you for your answer. i have solve the problem. it is a error from my proxy.thank you for your answer again!
